# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'module-main' do

  pod 'Masonry'
  pod 'NXHModule1',:path => '/Users/niuxinghua/Desktop/ios/模块化子工程'
  
end
