# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'module-main' do

  pod 'Masonry'
  pod 'NXHModule2',:path => '/Users/niuxinghua/Desktop/ios/module-main/module-main/module-demo2'
  
end
